const exception = require('./custom-exception')
module.exports = { exception }